const AVAILABLE_MODELS = [
  {
    id: 'gemma-2-2b-it',
    category: 'General Purpose',
    name: 'Gemma 2 (2B IT)',
    description:
      "Google's lightweight, state-of-the-art open model, optimized for instruction following.",
    size: '2.15 GB',
    minRam: 4,
    author: 'Google',
    hfUrl: 'https://huggingface.co/google/gemma-2-2b-it',
    source: 'Hugging Face',
    url: 'https://huggingface.co/google/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-q6_k.gguf',
    isEnabled: true,
  },
  {
    id: 'phi-3.5-mini-4k-instruct',
    category: 'General Purpose',
    name: 'Phi 3.5 Mini (4K)',
    description:
      'A lightweight, high-performance model by Microsoft focusing on reasoning and logic.',
    size: '2.39 GB',
    minRam: 4,
    author: 'Microsoft',
    hfUrl: 'https://huggingface.co/microsoft/Phi-3.5-mini-instruct',
    source: 'Hugging Face',
    url: 'https://huggingface.co/microsoft/Phi-3.5-mini-instruct-GGUF/resolve/main/phi-3.5-mini-instruct-q4_k_m.gguf',
    isEnabled: true,
  },
  {
    id: 'qwen2.5-1.5b-instruct',
    category: 'General Purpose',
    name: 'Qwen 2.5 (1.5B)',
    description:
      'The best all-rounder. Fast, multilingual, and very smart for its size.',
    size: '1.89 GB',
    minRam: 4,
    author: 'Alibaba (Qwen Team)',
    hfUrl: 'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct',
    source: 'Hugging Face',
    url: 'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_0.gguf',
    isEnabled: true,
  },
  {
    id: 'qwen2.5-3b-instruct',
    category: 'General Purpose',
    name: 'Qwen 2.5 (3B)',
    description:
      'A more powerful version of Qwen 2.5 with enhanced reasoning and coding capabilities.',
    size: '2.44 GB',
    minRam: 6,
    author: 'Alibaba (Qwen Team)',
    hfUrl: 'https://huggingface.co/Qwen/Qwen2.5-3B-Instruct',
    source: 'Hugging Face',
    url: 'https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q5_k_m.gguf',
    isEnabled: true,
  },
  {
    id: 'llama-3.2-1b-instruct',
    category: 'General Purpose',
    name: 'Llama 3.2 (1B)',
    description:
      "Meta's ultra-lightweight model designed for mobile and edge efficiency.",
    size: '1.32 GB',
    minRam: 2,
    author: 'Meta',
    hfUrl: 'https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct',
    source: 'Hugging Face',
    url: 'https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct-GGUF/resolve/main/llama-3.2-1b-instruct-q8_0.gguf',
    isEnabled: true,
  },
  {
    id: 'llama-3.2-3b-instruct',
    category: 'General Purpose',
    name: 'Llama 3.2 (3B)',
    description:
      'The balanced Llama 3.2 model for higher quality instruction following.',
    size: '2.64 GB',
    minRam: 6,
    author: 'Meta',
    hfUrl: 'https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct',
    source: 'Hugging Face',
    url: 'https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct-GGUF/resolve/main/llama-3.2-3b-instruct-q6_k.gguf',
    isEnabled: true,
  },
  {
    id: 'smollm2-1.7b-instruct',
    category: 'General Purpose',
    name: 'SmolLM2 (1.7B)',
    description:
      'A very small but surprisingly capable model trained on high-quality data.',
    size: '1.82 GB',
    minRam: 4,
    author: 'Hugging Face',
    hfUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct',
    source: 'Hugging Face',
    url: 'https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF/resolve/main/smollm2-1.7b-instruct-q8_0.gguf',
    isEnabled: true,
  },
  {
    id: 'smolvlm2-500m-instruct',
    category: 'Multimodal',
    name: 'SmolVLM2 (500M)',
    description:
      'A tiny vision-language model capable of understanding images.',
    size: '436.81 MB',
    minRam: 2,
    author: 'Hugging Face',
    hfUrl: 'https://huggingface.co/HuggingFaceTB/SmolVLM2-500M-Instruct',
    source: 'Hugging Face',
    url: 'https://huggingface.co/HuggingFaceTB/SmolVLM2-500M-Instruct-GGUF/resolve/main/smolvlm2-500m-instruct-q8_0.gguf',
    isEnabled: true,
  },
];

export { AVAILABLE_MODELS };
